# -*- coding: utf-8 -*-
"""ListaPython.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JYrM83pZlXp03uLJBzPAKdyd8wvuafhy
"""

# Questão 1 

Mensagem = 'Bem-vindo ao mundo da programação!'
print(Mensagem)

# Questão 2

numero = input('Digite um numero inteiro:')
numero = int(numero)
dobro = 2*numero
print('O dobro do número é: ',dobro)

# Questão 3

n1 = input('Digite o primeiro número: ')
n2 = input('Digite o segundo número: ')
n1 = int(n1)
n2 = int (n2)

soma =n1+n2

print('A soma dos números é: ', soma)

# Questão 4

base = input('Digite a base do triângulo: ')
altura = input('Digite a altura do triangulo: ')
base = float(base)
altura = float(altura)

Area = (base * altura)/2

print('A área do triângulo é igual a:{0} '.format(Area) )

# Questão 5

nome = input('Digite o nome de uma pessoa: ')
sobrenome = input('Digite o sobrenome dela: ')
print(sobrenome,',',nome)

# Questão 6

dolar = input('Digite um valor em dólar US$: ')
cotacao = input('Digite a cotação do dólar em reais: ')
dolar = float(dolar)
cotacao= float(cotacao)
resultado = dolar *cotacao
print('O valor em reais é R$:', resultado)

# Questão 7

quilo = 25.00
quilo=float(quilo)
peso = input('Qual o peso do prato em Kg: ')
peso=float(peso)
resultado = quilo * peso
print('O valor a pagar é R$:', resultado)

#Questão 8 

nome = input('Digite o nome do aluno: ')
nota1= float(input('Digite a primeira nota do aluno: '))
nota2=float(input('Digite a segunda nota do aluno: '))
nota3=float(input('Digite a terceira nota do aluno: '))

media = (nota1+nota2+nota3)/3

print(f'{nome} recebeu a média :',media)